name: Weekly Scholar Classifier

on:
  schedule:
    - cron: '0 0 * * MON'  # Runs at 00:00 every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-classifier:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create config files from template
      run: |
        cp config.example.yml config.yml
        
    - name: Run Scholar Classifier
      env:
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
      run: python scholar_classifier.py
