name: Markdown Spell Check

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.mdx'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.{md,mdx}"
          config: .cspell.json
